<div class="tables">
    <table>        
        <thead>
            <tr>
               <th>Category</th>
               <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>id</td>
                <td>{id}</td>
            </tr>
            <tr>
                <td>manufacturer</td>
                <td>{Manufacturer}</td>
            </tr>
            <tr>
                <td>model</td>
                <td>{Model}</td>
            </tr>
            <tr>
                <td>price</td>
                <td>{Price}</td>
            </tr>
            <tr>
                <td>seats</td>
                <td>{Seats}</td>
            </tr>
            <tr>
                <td>reach</td>
                <td>{Reach}</td>
            </tr>
            <tr>
                <td>cruise</td>
                <td>{Cruise}</td>
            </tr>
            <tr>
                <td>takeoff</td>
                <td>{Takeoff}</td>
            </tr>
            <tr>
                <td>hourly</td>
                <td>{Hourly}</td>
            </tr>
        </tbody>
    </table>
</div>
