<div>
    <table>        
        <thead>
            <tr>
               <th>Category</th>
               <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>id</td>
                <td>{id}</td>
            </tr>
            <tr>
                <td>manufacturer</td>
                <td>{manufacturer}</td>
            </tr>
            <tr>
                <td>model</td>
                <td>{model}</td>
            </tr>
            <tr>
                <td>seats</td>
                <td>{seats}</td>
            </tr>
            <tr>
                <td>reach</td>
                <td>{reach}</td>
            </tr>
            <tr>
                <td>cruise</td>
                <td>{cruise}</td>
            </tr>
            <tr>
                <td>takeoff</td>
                <td>{takeoff}</td>
            </tr>
            <tr>
                <td>hourly</td>
                <td>{hourly}</td>
            </tr>
        </tbody>
    </table>
</div>
